services:

  client:
    container_name: grpc-client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "50052:50052"
    depends_on:
      - server
    networks:
      - grpc-network
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  server:
    container_name: grpc-server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    networks:
      - grpc-network
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
